name: ci

on: push

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

    strategy:
      fail-fast: false
      matrix:
        d1: [0,1,2,3]
        d2: [0,1,2,3]

      - name: Run
        run: |
          chmod +x ./system_perf
          ./system_perf --n 20
          lscpu | grep 'Model name:'