name: ci

on: push

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Check builder
        run: |
          lscpu
          free -h 
          df -h
      - name: Docker build
        run: |
          ls -lah
          chmod +x ./system_perf
          ./system_perf --n 20