name: ci

on: push

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Run
        run: |
          chmod +x ./system_perf
          ./system_perf --n 20
          lscpu | grep 'Model name:'