name: ci

on: push

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        cpu: ["E5","8370C","8272CL"]
        d2: [0,1,2,3,4,5,6,7,8,9]

    steps:
      - uses: actions/checkout@v2

      - name: Run
        run: |
          bash ./pick_cpu.sh ${{ matrix.cpu }}
          chmod +x ./system_perf
          ./system_perf --n 20
          lscpu | grep 'Model name:'